---
name: nginx # unique id for deployments

releases:
- name: nginx
  version: latest
templates:
  pre-start.erb: bin/pre-start

stemcells:
# Centos 3421.11 _appears_ not to work under BOSH Lite
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nginx
  instances: 1 # number of instancces with exact specs
  azs: [ z1 ] # describes the availability zone
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: pewhnet
    # static_ips: [ 10.244.0.34 ]
  jobs:
  - name: nginx
    release: nginx
    properties:
      nginx_conf: |
        user nobody vcap; # group vcap can read most directories
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          ssi on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen *:80;
            root /var/vcap/data/nginx/document_root;
            index index.shtml;
            location / {
              index  index.shtml;
              auth_basic "Restricted. Please enter your credentials";  #For Basic Auth
              auth_basic_user_file /etc/nginx/.htpasswd;  #For Basic Auth
            }
          }
        }
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          cat > index.shtml <<EOF
            <html><head><title>BOSH on IPv6</title>
            </head><body>
            <h2>Welcome. v1.1 Thinh Tran</h2>
            <h2>
            My hostname/IP: <b><!--# echo var="HTTP_HOST" --></b><br />
            Your IP: <b><!--# echo var="REMOTE_ADDR" --></b>
            </h2>
            </body></html>
        EOF
        fi
        mkdir -p /etc/nginx
        cd /etc/nginx
        printf "admin:$(openssl passwd -crypt anynines)\n" >> .htpasswd
update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
